version: "3.9"

services:
  web_frontend:
    build:
      context: ../../..
      dockerfile: src/apps/5_web_frontend/Dockerfile
    entrypoint: ["/app/entrypoint.sh"]
    ports:
      - "8005:8005"
