version: "3.9"

services:
  service_frontend:
    build:
      context: ../../..
      dockerfile: src/apps/7_service_frontend/Dockerfile
    entrypoint: ["/app/entrypoint.sh"]
    env_file:
      - .env
    environment:
      SERVICE_HOST: "0.0.0.0"
      SERVICE_PORT: "8007"
    ports:
      - "8007:8007"
